#!/bin/sh
#
# memcached    Startup script for memcached processes
#
# chkconfig: - 90 10
# description: Memcache provides fast memory based storage.
# processname: memcached

# These mappings correspond one-to-one with Drupal's settings.php file.


exec 2>&1
ulimit -n 100000
ulimit -u 10240
export PATH=/command:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin
source /etc/profile.d/netflix_environment.sh
. /etc/rc.d/init.d/functions
. /etc/profile.d/netflix_environment.sh
service=memcache
subsys_lock="/var/lock/subsys/${service}"

let MB=`free -m | grep '^Mem:' | awk '{print $2}'`

if [ $MB -lt 7000 ] ; then
    echo "total memory = $MB MB, heap too small"
    exit 0
fi

# r3.large - leave previous algo, larger memory, use new one
# new: 2 GB for other apps, 1.5GB for networking overhead
if [ $MB -gt 20000 ]; then
    let CACHESIZE=`/usr/bin/python -c "print int(($MB-2000-1500)/1.03)"`
else
    let CACHESIZE=($MB/1000*1000)-2000
fi

command="/apps/memcached/bin/memcached"

[ -f memcached ] || exit 0

prog="memcached"

start() {
    echo -n $"Starting $prog "
    exec /usr/local/bin/setuidgid $userowner $command -p 11211 -u $NETFLIX_APPUSER -l 0.0.0.0 -c 100000 -o slab_reassign -o lru_maintainer,lru_crawler,hash_algorithm=murmur3 -I 2m -m $CACHESIZE
    RETVAL=$?
    echo
    return $RETVAL
}

stop() {
    if test "x`pidof memcached`" != x; then
        echo -n $"Stopping $prog "
        killall memcached
        echo
    fi
    RETVAL=$?
    return $RETVAL
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;
        condrestart)
            if test "x`pidof memcached`" != x; then
                stop
                start
            fi
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart|condrestart}"
            exit 1

esac

exit $RETVAL
